/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReactionType = IDL.Variant({
  'support' : IDL.Null,
  'helpful' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostType = IDL.Variant({
  'question' : IDL.Null,
  'story' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'parentCommentId' : IDL.Opt(IDL.Nat),
  'body' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const ReportReason = IDL.Variant({
  'abuse' : IDL.Null,
  'other' : IDL.Null,
  'spam' : IDL.Null,
  'offTopic' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'isComment' : IDL.Bool,
  'reportedId' : IDL.Nat,
  'reporter' : IDL.Principal,
  'reason' : ReportReason,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countPostReactions' : IDL.Func(
      [IDL.Nat, ReactionType],
      [IDL.Nat],
      ['query'],
    ),
  'createComment' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func(
      [PostType, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllPostsSorted' : IDL.Func([IDL.Bool], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getCommunityGuidelines' : IDL.Func([], [IDL.Text], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostsByType' : IDL.Func([IDL.Opt(PostType)], [IDL.Vec(Post)], ['query']),
  'getRepliesByComment' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
  'reportContent' : IDL.Func([IDL.Nat, IDL.Bool, ReportReason], [], []),
  'reviewSubmittedReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReactionType = IDL.Variant({
    'support' : IDL.Null,
    'helpful' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostType = IDL.Variant({ 'question' : IDL.Null, 'story' : IDL.Null });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'parentCommentId' : IDL.Opt(IDL.Nat),
    'body' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const ReportReason = IDL.Variant({
    'abuse' : IDL.Null,
    'other' : IDL.Null,
    'spam' : IDL.Null,
    'offTopic' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'isComment' : IDL.Bool,
    'reportedId' : IDL.Nat,
    'reporter' : IDL.Principal,
    'reason' : ReportReason,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countPostReactions' : IDL.Func(
        [IDL.Nat, ReactionType],
        [IDL.Nat],
        ['query'],
      ),
    'createComment' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [PostType, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllPostsSorted' : IDL.Func([IDL.Bool], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getCommunityGuidelines' : IDL.Func([], [IDL.Text], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostsByType' : IDL.Func(
        [IDL.Opt(PostType)],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getRepliesByComment' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeReaction' : IDL.Func([IDL.Nat, ReactionType], [], []),
    'reportContent' : IDL.Func([IDL.Nat, IDL.Bool, ReportReason], [], []),
    'reviewSubmittedReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };