/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'parentCommentId' : [] | [bigint],
  'body' : string,
  'createdAt' : Time,
  'author' : Principal,
  'postId' : bigint,
}
export interface Post {
  'id' : bigint,
  'postType' : PostType,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'author' : Principal,
}
export type PostType = { 'question' : null } |
  { 'story' : null };
export type ReactionType = { 'support' : null } |
  { 'helpful' : null };
export interface Report {
  'id' : bigint,
  'createdAt' : Time,
  'isComment' : boolean,
  'reportedId' : bigint,
  'reporter' : Principal,
  'reason' : ReportReason,
}
export type ReportReason = { 'abuse' : null } |
  { 'other' : null } |
  { 'spam' : null } |
  { 'offTopic' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countPostReactions' : ActorMethod<[bigint, ReactionType], bigint>,
  'createComment' : ActorMethod<[bigint, [] | [bigint], string], bigint>,
  'createPost' : ActorMethod<[PostType, string, string, Array<string>], bigint>,
  'getAllPostsSorted' : ActorMethod<[boolean], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPost' : ActorMethod<[bigint], Array<Comment>>,
  'getCommunityGuidelines' : ActorMethod<[], string>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostsByType' : ActorMethod<[[] | [PostType]], Array<Post>>,
  'getRepliesByComment' : ActorMethod<[bigint], Array<Comment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeReaction' : ActorMethod<[bigint, ReactionType], undefined>,
  'reportContent' : ActorMethod<[bigint, boolean, ReportReason], undefined>,
  'reviewSubmittedReports' : ActorMethod<[], Array<Report>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];